[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "phyloNEON"
authors = [{name = "Hugh Cross", email = "crossh@battelleecology.org"}]
dynamic = ["version", "description"]
